//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BFM.Server.DataAsset.WMSService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://fanuc.com.cn/", ConfigurationName="WMSService.IWMSService")]
    public interface IWMSService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IWMSService/GetWmsAreaInfoByPage", ReplyAction="http://fanuc.com.cn/IWMSService/GetWmsAreaInfoByPageResponse")]
        System.Collections.Generic.List<BFM.ContractModel.WmsAreaInfo> GetWmsAreaInfoByPage(int pageSize, int pageIndex, bool isAsc, string orderField, string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IWMSService/GetWmsAreaInfoByPage", ReplyAction="http://fanuc.com.cn/IWMSService/GetWmsAreaInfoByPageResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BFM.ContractModel.WmsAreaInfo>> GetWmsAreaInfoByPageAsync(int pageSize, int pageIndex, bool isAsc, string orderField, string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IWMSService/GetWmsAreaInfoCount", ReplyAction="http://fanuc.com.cn/IWMSService/GetWmsAreaInfoCountResponse")]
        int GetWmsAreaInfoCount(string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IWMSService/GetWmsAreaInfoCount", ReplyAction="http://fanuc.com.cn/IWMSService/GetWmsAreaInfoCountResponse")]
        System.Threading.Tasks.Task<int> GetWmsAreaInfoCountAsync(string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IWMSService/AddWmsAreaInfo", ReplyAction="http://fanuc.com.cn/IWMSService/AddWmsAreaInfoResponse")]
        bool AddWmsAreaInfo(BFM.ContractModel.WmsAreaInfo mWmsAreaInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IWMSService/AddWmsAreaInfo", ReplyAction="http://fanuc.com.cn/IWMSService/AddWmsAreaInfoResponse")]
        System.Threading.Tasks.Task<bool> AddWmsAreaInfoAsync(BFM.ContractModel.WmsAreaInfo mWmsAreaInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IWMSService/UpdateWmsAreaInfo", ReplyAction="http://fanuc.com.cn/IWMSService/UpdateWmsAreaInfoResponse")]
        bool UpdateWmsAreaInfo(BFM.ContractModel.WmsAreaInfo mWmsAreaInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IWMSService/UpdateWmsAreaInfo", ReplyAction="http://fanuc.com.cn/IWMSService/UpdateWmsAreaInfoResponse")]
        System.Threading.Tasks.Task<bool> UpdateWmsAreaInfoAsync(BFM.ContractModel.WmsAreaInfo mWmsAreaInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IWMSService/DelWmsAreaInfos", ReplyAction="http://fanuc.com.cn/IWMSService/DelWmsAreaInfosResponse")]
        bool DelWmsAreaInfos(System.Collections.Generic.List<string> Ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IWMSService/DelWmsAreaInfos", ReplyAction="http://fanuc.com.cn/IWMSService/DelWmsAreaInfosResponse")]
        System.Threading.Tasks.Task<bool> DelWmsAreaInfosAsync(System.Collections.Generic.List<string> Ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IWMSService/DelWmsAreaInfo", ReplyAction="http://fanuc.com.cn/IWMSService/DelWmsAreaInfoResponse")]
        bool DelWmsAreaInfo(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IWMSService/DelWmsAreaInfo", ReplyAction="http://fanuc.com.cn/IWMSService/DelWmsAreaInfoResponse")]
        System.Threading.Tasks.Task<bool> DelWmsAreaInfoAsync(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IWMSService/GetWmsAreaInfos", ReplyAction="http://fanuc.com.cn/IWMSService/GetWmsAreaInfosResponse")]
        System.Collections.Generic.List<BFM.ContractModel.WmsAreaInfo> GetWmsAreaInfos(string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IWMSService/GetWmsAreaInfos", ReplyAction="http://fanuc.com.cn/IWMSService/GetWmsAreaInfosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BFM.ContractModel.WmsAreaInfo>> GetWmsAreaInfosAsync(string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IWMSService/GetWmsAreaInfoById", ReplyAction="http://fanuc.com.cn/IWMSService/GetWmsAreaInfoByIdResponse")]
        BFM.ContractModel.WmsAreaInfo GetWmsAreaInfoById(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IWMSService/GetWmsAreaInfoById", ReplyAction="http://fanuc.com.cn/IWMSService/GetWmsAreaInfoByIdResponse")]
        System.Threading.Tasks.Task<BFM.ContractModel.WmsAreaInfo> GetWmsAreaInfoByIdAsync(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IWMSService/GetWmsAllocationInfoByPage", ReplyAction="http://fanuc.com.cn/IWMSService/GetWmsAllocationInfoByPageResponse")]
        System.Collections.Generic.List<BFM.ContractModel.WmsAllocationInfo> GetWmsAllocationInfoByPage(int pageSize, int pageIndex, bool isAsc, string orderField, string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IWMSService/GetWmsAllocationInfoByPage", ReplyAction="http://fanuc.com.cn/IWMSService/GetWmsAllocationInfoByPageResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BFM.ContractModel.WmsAllocationInfo>> GetWmsAllocationInfoByPageAsync(int pageSize, int pageIndex, bool isAsc, string orderField, string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IWMSService/GetWmsAllocationInfoCount", ReplyAction="http://fanuc.com.cn/IWMSService/GetWmsAllocationInfoCountResponse")]
        int GetWmsAllocationInfoCount(string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IWMSService/GetWmsAllocationInfoCount", ReplyAction="http://fanuc.com.cn/IWMSService/GetWmsAllocationInfoCountResponse")]
        System.Threading.Tasks.Task<int> GetWmsAllocationInfoCountAsync(string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IWMSService/AddWmsAllocationInfo", ReplyAction="http://fanuc.com.cn/IWMSService/AddWmsAllocationInfoResponse")]
        bool AddWmsAllocationInfo(BFM.ContractModel.WmsAllocationInfo mWmsAllocationInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IWMSService/AddWmsAllocationInfo", ReplyAction="http://fanuc.com.cn/IWMSService/AddWmsAllocationInfoResponse")]
        System.Threading.Tasks.Task<bool> AddWmsAllocationInfoAsync(BFM.ContractModel.WmsAllocationInfo mWmsAllocationInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IWMSService/UpdateWmsAllocationInfo", ReplyAction="http://fanuc.com.cn/IWMSService/UpdateWmsAllocationInfoResponse")]
        bool UpdateWmsAllocationInfo(BFM.ContractModel.WmsAllocationInfo mWmsAllocationInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IWMSService/UpdateWmsAllocationInfo", ReplyAction="http://fanuc.com.cn/IWMSService/UpdateWmsAllocationInfoResponse")]
        System.Threading.Tasks.Task<bool> UpdateWmsAllocationInfoAsync(BFM.ContractModel.WmsAllocationInfo mWmsAllocationInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IWMSService/DelWmsAllocationInfos", ReplyAction="http://fanuc.com.cn/IWMSService/DelWmsAllocationInfosResponse")]
        bool DelWmsAllocationInfos(System.Collections.Generic.List<string> Ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IWMSService/DelWmsAllocationInfos", ReplyAction="http://fanuc.com.cn/IWMSService/DelWmsAllocationInfosResponse")]
        System.Threading.Tasks.Task<bool> DelWmsAllocationInfosAsync(System.Collections.Generic.List<string> Ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IWMSService/DelWmsAllocationInfo", ReplyAction="http://fanuc.com.cn/IWMSService/DelWmsAllocationInfoResponse")]
        bool DelWmsAllocationInfo(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IWMSService/DelWmsAllocationInfo", ReplyAction="http://fanuc.com.cn/IWMSService/DelWmsAllocationInfoResponse")]
        System.Threading.Tasks.Task<bool> DelWmsAllocationInfoAsync(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IWMSService/GetWmsAllocationInfos", ReplyAction="http://fanuc.com.cn/IWMSService/GetWmsAllocationInfosResponse")]
        System.Collections.Generic.List<BFM.ContractModel.WmsAllocationInfo> GetWmsAllocationInfos(string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IWMSService/GetWmsAllocationInfos", ReplyAction="http://fanuc.com.cn/IWMSService/GetWmsAllocationInfosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BFM.ContractModel.WmsAllocationInfo>> GetWmsAllocationInfosAsync(string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IWMSService/GetWmsAllocationInfoById", ReplyAction="http://fanuc.com.cn/IWMSService/GetWmsAllocationInfoByIdResponse")]
        BFM.ContractModel.WmsAllocationInfo GetWmsAllocationInfoById(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IWMSService/GetWmsAllocationInfoById", ReplyAction="http://fanuc.com.cn/IWMSService/GetWmsAllocationInfoByIdResponse")]
        System.Threading.Tasks.Task<BFM.ContractModel.WmsAllocationInfo> GetWmsAllocationInfoByIdAsync(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IWMSService/GetWmsInvOperateByPage", ReplyAction="http://fanuc.com.cn/IWMSService/GetWmsInvOperateByPageResponse")]
        System.Collections.Generic.List<BFM.ContractModel.WmsInvOperate> GetWmsInvOperateByPage(int pageSize, int pageIndex, bool isAsc, string orderField, string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IWMSService/GetWmsInvOperateByPage", ReplyAction="http://fanuc.com.cn/IWMSService/GetWmsInvOperateByPageResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BFM.ContractModel.WmsInvOperate>> GetWmsInvOperateByPageAsync(int pageSize, int pageIndex, bool isAsc, string orderField, string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IWMSService/GetWmsInvOperateCount", ReplyAction="http://fanuc.com.cn/IWMSService/GetWmsInvOperateCountResponse")]
        int GetWmsInvOperateCount(string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IWMSService/GetWmsInvOperateCount", ReplyAction="http://fanuc.com.cn/IWMSService/GetWmsInvOperateCountResponse")]
        System.Threading.Tasks.Task<int> GetWmsInvOperateCountAsync(string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IWMSService/AddWmsInvOperate", ReplyAction="http://fanuc.com.cn/IWMSService/AddWmsInvOperateResponse")]
        bool AddWmsInvOperate(BFM.ContractModel.WmsInvOperate mWmsInvOperate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IWMSService/AddWmsInvOperate", ReplyAction="http://fanuc.com.cn/IWMSService/AddWmsInvOperateResponse")]
        System.Threading.Tasks.Task<bool> AddWmsInvOperateAsync(BFM.ContractModel.WmsInvOperate mWmsInvOperate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IWMSService/UpdateWmsInvOperate", ReplyAction="http://fanuc.com.cn/IWMSService/UpdateWmsInvOperateResponse")]
        bool UpdateWmsInvOperate(BFM.ContractModel.WmsInvOperate mWmsInvOperate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IWMSService/UpdateWmsInvOperate", ReplyAction="http://fanuc.com.cn/IWMSService/UpdateWmsInvOperateResponse")]
        System.Threading.Tasks.Task<bool> UpdateWmsInvOperateAsync(BFM.ContractModel.WmsInvOperate mWmsInvOperate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IWMSService/DelWmsInvOperates", ReplyAction="http://fanuc.com.cn/IWMSService/DelWmsInvOperatesResponse")]
        bool DelWmsInvOperates(System.Collections.Generic.List<string> Ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IWMSService/DelWmsInvOperates", ReplyAction="http://fanuc.com.cn/IWMSService/DelWmsInvOperatesResponse")]
        System.Threading.Tasks.Task<bool> DelWmsInvOperatesAsync(System.Collections.Generic.List<string> Ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IWMSService/DelWmsInvOperate", ReplyAction="http://fanuc.com.cn/IWMSService/DelWmsInvOperateResponse")]
        bool DelWmsInvOperate(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IWMSService/DelWmsInvOperate", ReplyAction="http://fanuc.com.cn/IWMSService/DelWmsInvOperateResponse")]
        System.Threading.Tasks.Task<bool> DelWmsInvOperateAsync(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IWMSService/GetWmsInvOperates", ReplyAction="http://fanuc.com.cn/IWMSService/GetWmsInvOperatesResponse")]
        System.Collections.Generic.List<BFM.ContractModel.WmsInvOperate> GetWmsInvOperates(string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IWMSService/GetWmsInvOperates", ReplyAction="http://fanuc.com.cn/IWMSService/GetWmsInvOperatesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BFM.ContractModel.WmsInvOperate>> GetWmsInvOperatesAsync(string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IWMSService/GetWmsInvOperateById", ReplyAction="http://fanuc.com.cn/IWMSService/GetWmsInvOperateByIdResponse")]
        BFM.ContractModel.WmsInvOperate GetWmsInvOperateById(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IWMSService/GetWmsInvOperateById", ReplyAction="http://fanuc.com.cn/IWMSService/GetWmsInvOperateByIdResponse")]
        System.Threading.Tasks.Task<BFM.ContractModel.WmsInvOperate> GetWmsInvOperateByIdAsync(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IWMSService/GetWmsInventoryByPage", ReplyAction="http://fanuc.com.cn/IWMSService/GetWmsInventoryByPageResponse")]
        System.Collections.Generic.List<BFM.ContractModel.WmsInventory> GetWmsInventoryByPage(int pageSize, int pageIndex, bool isAsc, string orderField, string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IWMSService/GetWmsInventoryByPage", ReplyAction="http://fanuc.com.cn/IWMSService/GetWmsInventoryByPageResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BFM.ContractModel.WmsInventory>> GetWmsInventoryByPageAsync(int pageSize, int pageIndex, bool isAsc, string orderField, string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IWMSService/GetWmsInventoryCount", ReplyAction="http://fanuc.com.cn/IWMSService/GetWmsInventoryCountResponse")]
        int GetWmsInventoryCount(string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IWMSService/GetWmsInventoryCount", ReplyAction="http://fanuc.com.cn/IWMSService/GetWmsInventoryCountResponse")]
        System.Threading.Tasks.Task<int> GetWmsInventoryCountAsync(string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IWMSService/AddWmsInventory", ReplyAction="http://fanuc.com.cn/IWMSService/AddWmsInventoryResponse")]
        bool AddWmsInventory(BFM.ContractModel.WmsInventory mWmsInventory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IWMSService/AddWmsInventory", ReplyAction="http://fanuc.com.cn/IWMSService/AddWmsInventoryResponse")]
        System.Threading.Tasks.Task<bool> AddWmsInventoryAsync(BFM.ContractModel.WmsInventory mWmsInventory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IWMSService/UpdateWmsInventory", ReplyAction="http://fanuc.com.cn/IWMSService/UpdateWmsInventoryResponse")]
        bool UpdateWmsInventory(BFM.ContractModel.WmsInventory mWmsInventory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IWMSService/UpdateWmsInventory", ReplyAction="http://fanuc.com.cn/IWMSService/UpdateWmsInventoryResponse")]
        System.Threading.Tasks.Task<bool> UpdateWmsInventoryAsync(BFM.ContractModel.WmsInventory mWmsInventory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IWMSService/DelWmsInventorys", ReplyAction="http://fanuc.com.cn/IWMSService/DelWmsInventorysResponse")]
        bool DelWmsInventorys(System.Collections.Generic.List<string> Ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IWMSService/DelWmsInventorys", ReplyAction="http://fanuc.com.cn/IWMSService/DelWmsInventorysResponse")]
        System.Threading.Tasks.Task<bool> DelWmsInventorysAsync(System.Collections.Generic.List<string> Ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IWMSService/DelWmsInventory", ReplyAction="http://fanuc.com.cn/IWMSService/DelWmsInventoryResponse")]
        bool DelWmsInventory(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IWMSService/DelWmsInventory", ReplyAction="http://fanuc.com.cn/IWMSService/DelWmsInventoryResponse")]
        System.Threading.Tasks.Task<bool> DelWmsInventoryAsync(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IWMSService/GetWmsInventorys", ReplyAction="http://fanuc.com.cn/IWMSService/GetWmsInventorysResponse")]
        System.Collections.Generic.List<BFM.ContractModel.WmsInventory> GetWmsInventorys(string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IWMSService/GetWmsInventorys", ReplyAction="http://fanuc.com.cn/IWMSService/GetWmsInventorysResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BFM.ContractModel.WmsInventory>> GetWmsInventorysAsync(string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IWMSService/GetWmsInventoryById", ReplyAction="http://fanuc.com.cn/IWMSService/GetWmsInventoryByIdResponse")]
        BFM.ContractModel.WmsInventory GetWmsInventoryById(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IWMSService/GetWmsInventoryById", ReplyAction="http://fanuc.com.cn/IWMSService/GetWmsInventoryByIdResponse")]
        System.Threading.Tasks.Task<BFM.ContractModel.WmsInventory> GetWmsInventoryByIdAsync(string Id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWMSServiceChannel : BFM.Server.DataAsset.WMSService.IWMSService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WMSServiceClient : System.ServiceModel.ClientBase<BFM.Server.DataAsset.WMSService.IWMSService>, BFM.Server.DataAsset.WMSService.IWMSService {
        
        public WMSServiceClient() {
        }
        
        public WMSServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WMSServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WMSServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WMSServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<BFM.ContractModel.WmsAreaInfo> GetWmsAreaInfoByPage(int pageSize, int pageIndex, bool isAsc, string orderField, string sWhere) {
            return base.Channel.GetWmsAreaInfoByPage(pageSize, pageIndex, isAsc, orderField, sWhere);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BFM.ContractModel.WmsAreaInfo>> GetWmsAreaInfoByPageAsync(int pageSize, int pageIndex, bool isAsc, string orderField, string sWhere) {
            return base.Channel.GetWmsAreaInfoByPageAsync(pageSize, pageIndex, isAsc, orderField, sWhere);
        }
        
        public int GetWmsAreaInfoCount(string sWhere) {
            return base.Channel.GetWmsAreaInfoCount(sWhere);
        }
        
        public System.Threading.Tasks.Task<int> GetWmsAreaInfoCountAsync(string sWhere) {
            return base.Channel.GetWmsAreaInfoCountAsync(sWhere);
        }
        
        public bool AddWmsAreaInfo(BFM.ContractModel.WmsAreaInfo mWmsAreaInfo) {
            return base.Channel.AddWmsAreaInfo(mWmsAreaInfo);
        }
        
        public System.Threading.Tasks.Task<bool> AddWmsAreaInfoAsync(BFM.ContractModel.WmsAreaInfo mWmsAreaInfo) {
            return base.Channel.AddWmsAreaInfoAsync(mWmsAreaInfo);
        }
        
        public bool UpdateWmsAreaInfo(BFM.ContractModel.WmsAreaInfo mWmsAreaInfo) {
            return base.Channel.UpdateWmsAreaInfo(mWmsAreaInfo);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateWmsAreaInfoAsync(BFM.ContractModel.WmsAreaInfo mWmsAreaInfo) {
            return base.Channel.UpdateWmsAreaInfoAsync(mWmsAreaInfo);
        }
        
        public bool DelWmsAreaInfos(System.Collections.Generic.List<string> Ids) {
            return base.Channel.DelWmsAreaInfos(Ids);
        }
        
        public System.Threading.Tasks.Task<bool> DelWmsAreaInfosAsync(System.Collections.Generic.List<string> Ids) {
            return base.Channel.DelWmsAreaInfosAsync(Ids);
        }
        
        public bool DelWmsAreaInfo(string Id) {
            return base.Channel.DelWmsAreaInfo(Id);
        }
        
        public System.Threading.Tasks.Task<bool> DelWmsAreaInfoAsync(string Id) {
            return base.Channel.DelWmsAreaInfoAsync(Id);
        }
        
        public System.Collections.Generic.List<BFM.ContractModel.WmsAreaInfo> GetWmsAreaInfos(string sWhere) {
            return base.Channel.GetWmsAreaInfos(sWhere);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BFM.ContractModel.WmsAreaInfo>> GetWmsAreaInfosAsync(string sWhere) {
            return base.Channel.GetWmsAreaInfosAsync(sWhere);
        }
        
        public BFM.ContractModel.WmsAreaInfo GetWmsAreaInfoById(string Id) {
            return base.Channel.GetWmsAreaInfoById(Id);
        }
        
        public System.Threading.Tasks.Task<BFM.ContractModel.WmsAreaInfo> GetWmsAreaInfoByIdAsync(string Id) {
            return base.Channel.GetWmsAreaInfoByIdAsync(Id);
        }
        
        public System.Collections.Generic.List<BFM.ContractModel.WmsAllocationInfo> GetWmsAllocationInfoByPage(int pageSize, int pageIndex, bool isAsc, string orderField, string sWhere) {
            return base.Channel.GetWmsAllocationInfoByPage(pageSize, pageIndex, isAsc, orderField, sWhere);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BFM.ContractModel.WmsAllocationInfo>> GetWmsAllocationInfoByPageAsync(int pageSize, int pageIndex, bool isAsc, string orderField, string sWhere) {
            return base.Channel.GetWmsAllocationInfoByPageAsync(pageSize, pageIndex, isAsc, orderField, sWhere);
        }
        
        public int GetWmsAllocationInfoCount(string sWhere) {
            return base.Channel.GetWmsAllocationInfoCount(sWhere);
        }
        
        public System.Threading.Tasks.Task<int> GetWmsAllocationInfoCountAsync(string sWhere) {
            return base.Channel.GetWmsAllocationInfoCountAsync(sWhere);
        }
        
        public bool AddWmsAllocationInfo(BFM.ContractModel.WmsAllocationInfo mWmsAllocationInfo) {
            return base.Channel.AddWmsAllocationInfo(mWmsAllocationInfo);
        }
        
        public System.Threading.Tasks.Task<bool> AddWmsAllocationInfoAsync(BFM.ContractModel.WmsAllocationInfo mWmsAllocationInfo) {
            return base.Channel.AddWmsAllocationInfoAsync(mWmsAllocationInfo);
        }
        
        public bool UpdateWmsAllocationInfo(BFM.ContractModel.WmsAllocationInfo mWmsAllocationInfo) {
            return base.Channel.UpdateWmsAllocationInfo(mWmsAllocationInfo);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateWmsAllocationInfoAsync(BFM.ContractModel.WmsAllocationInfo mWmsAllocationInfo) {
            return base.Channel.UpdateWmsAllocationInfoAsync(mWmsAllocationInfo);
        }
        
        public bool DelWmsAllocationInfos(System.Collections.Generic.List<string> Ids) {
            return base.Channel.DelWmsAllocationInfos(Ids);
        }
        
        public System.Threading.Tasks.Task<bool> DelWmsAllocationInfosAsync(System.Collections.Generic.List<string> Ids) {
            return base.Channel.DelWmsAllocationInfosAsync(Ids);
        }
        
        public bool DelWmsAllocationInfo(string Id) {
            return base.Channel.DelWmsAllocationInfo(Id);
        }
        
        public System.Threading.Tasks.Task<bool> DelWmsAllocationInfoAsync(string Id) {
            return base.Channel.DelWmsAllocationInfoAsync(Id);
        }
        
        public System.Collections.Generic.List<BFM.ContractModel.WmsAllocationInfo> GetWmsAllocationInfos(string sWhere) {
            return base.Channel.GetWmsAllocationInfos(sWhere);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BFM.ContractModel.WmsAllocationInfo>> GetWmsAllocationInfosAsync(string sWhere) {
            return base.Channel.GetWmsAllocationInfosAsync(sWhere);
        }
        
        public BFM.ContractModel.WmsAllocationInfo GetWmsAllocationInfoById(string Id) {
            return base.Channel.GetWmsAllocationInfoById(Id);
        }
        
        public System.Threading.Tasks.Task<BFM.ContractModel.WmsAllocationInfo> GetWmsAllocationInfoByIdAsync(string Id) {
            return base.Channel.GetWmsAllocationInfoByIdAsync(Id);
        }
        
        public System.Collections.Generic.List<BFM.ContractModel.WmsInvOperate> GetWmsInvOperateByPage(int pageSize, int pageIndex, bool isAsc, string orderField, string sWhere) {
            return base.Channel.GetWmsInvOperateByPage(pageSize, pageIndex, isAsc, orderField, sWhere);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BFM.ContractModel.WmsInvOperate>> GetWmsInvOperateByPageAsync(int pageSize, int pageIndex, bool isAsc, string orderField, string sWhere) {
            return base.Channel.GetWmsInvOperateByPageAsync(pageSize, pageIndex, isAsc, orderField, sWhere);
        }
        
        public int GetWmsInvOperateCount(string sWhere) {
            return base.Channel.GetWmsInvOperateCount(sWhere);
        }
        
        public System.Threading.Tasks.Task<int> GetWmsInvOperateCountAsync(string sWhere) {
            return base.Channel.GetWmsInvOperateCountAsync(sWhere);
        }
        
        public bool AddWmsInvOperate(BFM.ContractModel.WmsInvOperate mWmsInvOperate) {
            return base.Channel.AddWmsInvOperate(mWmsInvOperate);
        }
        
        public System.Threading.Tasks.Task<bool> AddWmsInvOperateAsync(BFM.ContractModel.WmsInvOperate mWmsInvOperate) {
            return base.Channel.AddWmsInvOperateAsync(mWmsInvOperate);
        }
        
        public bool UpdateWmsInvOperate(BFM.ContractModel.WmsInvOperate mWmsInvOperate) {
            return base.Channel.UpdateWmsInvOperate(mWmsInvOperate);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateWmsInvOperateAsync(BFM.ContractModel.WmsInvOperate mWmsInvOperate) {
            return base.Channel.UpdateWmsInvOperateAsync(mWmsInvOperate);
        }
        
        public bool DelWmsInvOperates(System.Collections.Generic.List<string> Ids) {
            return base.Channel.DelWmsInvOperates(Ids);
        }
        
        public System.Threading.Tasks.Task<bool> DelWmsInvOperatesAsync(System.Collections.Generic.List<string> Ids) {
            return base.Channel.DelWmsInvOperatesAsync(Ids);
        }
        
        public bool DelWmsInvOperate(string Id) {
            return base.Channel.DelWmsInvOperate(Id);
        }
        
        public System.Threading.Tasks.Task<bool> DelWmsInvOperateAsync(string Id) {
            return base.Channel.DelWmsInvOperateAsync(Id);
        }
        
        public System.Collections.Generic.List<BFM.ContractModel.WmsInvOperate> GetWmsInvOperates(string sWhere) {
            return base.Channel.GetWmsInvOperates(sWhere);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BFM.ContractModel.WmsInvOperate>> GetWmsInvOperatesAsync(string sWhere) {
            return base.Channel.GetWmsInvOperatesAsync(sWhere);
        }
        
        public BFM.ContractModel.WmsInvOperate GetWmsInvOperateById(string Id) {
            return base.Channel.GetWmsInvOperateById(Id);
        }
        
        public System.Threading.Tasks.Task<BFM.ContractModel.WmsInvOperate> GetWmsInvOperateByIdAsync(string Id) {
            return base.Channel.GetWmsInvOperateByIdAsync(Id);
        }
        
        public System.Collections.Generic.List<BFM.ContractModel.WmsInventory> GetWmsInventoryByPage(int pageSize, int pageIndex, bool isAsc, string orderField, string sWhere) {
            return base.Channel.GetWmsInventoryByPage(pageSize, pageIndex, isAsc, orderField, sWhere);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BFM.ContractModel.WmsInventory>> GetWmsInventoryByPageAsync(int pageSize, int pageIndex, bool isAsc, string orderField, string sWhere) {
            return base.Channel.GetWmsInventoryByPageAsync(pageSize, pageIndex, isAsc, orderField, sWhere);
        }
        
        public int GetWmsInventoryCount(string sWhere) {
            return base.Channel.GetWmsInventoryCount(sWhere);
        }
        
        public System.Threading.Tasks.Task<int> GetWmsInventoryCountAsync(string sWhere) {
            return base.Channel.GetWmsInventoryCountAsync(sWhere);
        }
        
        public bool AddWmsInventory(BFM.ContractModel.WmsInventory mWmsInventory) {
            return base.Channel.AddWmsInventory(mWmsInventory);
        }
        
        public System.Threading.Tasks.Task<bool> AddWmsInventoryAsync(BFM.ContractModel.WmsInventory mWmsInventory) {
            return base.Channel.AddWmsInventoryAsync(mWmsInventory);
        }
        
        public bool UpdateWmsInventory(BFM.ContractModel.WmsInventory mWmsInventory) {
            return base.Channel.UpdateWmsInventory(mWmsInventory);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateWmsInventoryAsync(BFM.ContractModel.WmsInventory mWmsInventory) {
            return base.Channel.UpdateWmsInventoryAsync(mWmsInventory);
        }
        
        public bool DelWmsInventorys(System.Collections.Generic.List<string> Ids) {
            return base.Channel.DelWmsInventorys(Ids);
        }
        
        public System.Threading.Tasks.Task<bool> DelWmsInventorysAsync(System.Collections.Generic.List<string> Ids) {
            return base.Channel.DelWmsInventorysAsync(Ids);
        }
        
        public bool DelWmsInventory(string Id) {
            return base.Channel.DelWmsInventory(Id);
        }
        
        public System.Threading.Tasks.Task<bool> DelWmsInventoryAsync(string Id) {
            return base.Channel.DelWmsInventoryAsync(Id);
        }
        
        public System.Collections.Generic.List<BFM.ContractModel.WmsInventory> GetWmsInventorys(string sWhere) {
            return base.Channel.GetWmsInventorys(sWhere);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BFM.ContractModel.WmsInventory>> GetWmsInventorysAsync(string sWhere) {
            return base.Channel.GetWmsInventorysAsync(sWhere);
        }
        
        public BFM.ContractModel.WmsInventory GetWmsInventoryById(string Id) {
            return base.Channel.GetWmsInventoryById(Id);
        }
        
        public System.Threading.Tasks.Task<BFM.ContractModel.WmsInventory> GetWmsInventoryByIdAsync(string Id) {
            return base.Channel.GetWmsInventoryByIdAsync(Id);
        }
    }
}
