//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BFM.Server.DataAsset.EAMService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://fanuc.com.cn/", ConfigurationName="EAMService.IEAMService")]
    public interface IEAMService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/GetAmAssetMasterNByPage", ReplyAction="http://fanuc.com.cn/IEAMService/GetAmAssetMasterNByPageResponse")]
        System.Collections.Generic.List<BFM.ContractModel.AmAssetMasterN> GetAmAssetMasterNByPage(int pageSize, int pageIndex, bool isAsc, string orderField, string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/GetAmAssetMasterNByPage", ReplyAction="http://fanuc.com.cn/IEAMService/GetAmAssetMasterNByPageResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BFM.ContractModel.AmAssetMasterN>> GetAmAssetMasterNByPageAsync(int pageSize, int pageIndex, bool isAsc, string orderField, string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/GetAmAssetMasterNCount", ReplyAction="http://fanuc.com.cn/IEAMService/GetAmAssetMasterNCountResponse")]
        int GetAmAssetMasterNCount(string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/GetAmAssetMasterNCount", ReplyAction="http://fanuc.com.cn/IEAMService/GetAmAssetMasterNCountResponse")]
        System.Threading.Tasks.Task<int> GetAmAssetMasterNCountAsync(string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/AddAmAssetMasterN", ReplyAction="http://fanuc.com.cn/IEAMService/AddAmAssetMasterNResponse")]
        bool AddAmAssetMasterN(BFM.ContractModel.AmAssetMasterN mAmAssetMasterN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/AddAmAssetMasterN", ReplyAction="http://fanuc.com.cn/IEAMService/AddAmAssetMasterNResponse")]
        System.Threading.Tasks.Task<bool> AddAmAssetMasterNAsync(BFM.ContractModel.AmAssetMasterN mAmAssetMasterN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/UpdateAmAssetMasterN", ReplyAction="http://fanuc.com.cn/IEAMService/UpdateAmAssetMasterNResponse")]
        bool UpdateAmAssetMasterN(BFM.ContractModel.AmAssetMasterN mAmAssetMasterN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/UpdateAmAssetMasterN", ReplyAction="http://fanuc.com.cn/IEAMService/UpdateAmAssetMasterNResponse")]
        System.Threading.Tasks.Task<bool> UpdateAmAssetMasterNAsync(BFM.ContractModel.AmAssetMasterN mAmAssetMasterN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/DelAmAssetMasterNs", ReplyAction="http://fanuc.com.cn/IEAMService/DelAmAssetMasterNsResponse")]
        bool DelAmAssetMasterNs(System.Collections.Generic.List<string> Ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/DelAmAssetMasterNs", ReplyAction="http://fanuc.com.cn/IEAMService/DelAmAssetMasterNsResponse")]
        System.Threading.Tasks.Task<bool> DelAmAssetMasterNsAsync(System.Collections.Generic.List<string> Ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/DelAmAssetMasterN", ReplyAction="http://fanuc.com.cn/IEAMService/DelAmAssetMasterNResponse")]
        bool DelAmAssetMasterN(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/DelAmAssetMasterN", ReplyAction="http://fanuc.com.cn/IEAMService/DelAmAssetMasterNResponse")]
        System.Threading.Tasks.Task<bool> DelAmAssetMasterNAsync(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/GetAmAssetMasterNs", ReplyAction="http://fanuc.com.cn/IEAMService/GetAmAssetMasterNsResponse")]
        System.Collections.Generic.List<BFM.ContractModel.AmAssetMasterN> GetAmAssetMasterNs(string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/GetAmAssetMasterNs", ReplyAction="http://fanuc.com.cn/IEAMService/GetAmAssetMasterNsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BFM.ContractModel.AmAssetMasterN>> GetAmAssetMasterNsAsync(string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/GetAmAssetMasterNById", ReplyAction="http://fanuc.com.cn/IEAMService/GetAmAssetMasterNByIdResponse")]
        BFM.ContractModel.AmAssetMasterN GetAmAssetMasterNById(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/GetAmAssetMasterNById", ReplyAction="http://fanuc.com.cn/IEAMService/GetAmAssetMasterNByIdResponse")]
        System.Threading.Tasks.Task<BFM.ContractModel.AmAssetMasterN> GetAmAssetMasterNByIdAsync(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/GetAmPartsMasterNByPage", ReplyAction="http://fanuc.com.cn/IEAMService/GetAmPartsMasterNByPageResponse")]
        System.Collections.Generic.List<BFM.ContractModel.AmPartsMasterN> GetAmPartsMasterNByPage(int pageSize, int pageIndex, bool isAsc, string orderField, string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/GetAmPartsMasterNByPage", ReplyAction="http://fanuc.com.cn/IEAMService/GetAmPartsMasterNByPageResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BFM.ContractModel.AmPartsMasterN>> GetAmPartsMasterNByPageAsync(int pageSize, int pageIndex, bool isAsc, string orderField, string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/GetAmPartsMasterNCount", ReplyAction="http://fanuc.com.cn/IEAMService/GetAmPartsMasterNCountResponse")]
        int GetAmPartsMasterNCount(string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/GetAmPartsMasterNCount", ReplyAction="http://fanuc.com.cn/IEAMService/GetAmPartsMasterNCountResponse")]
        System.Threading.Tasks.Task<int> GetAmPartsMasterNCountAsync(string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/AddAmPartsMasterN", ReplyAction="http://fanuc.com.cn/IEAMService/AddAmPartsMasterNResponse")]
        bool AddAmPartsMasterN(BFM.ContractModel.AmPartsMasterN mAmPartsMasterN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/AddAmPartsMasterN", ReplyAction="http://fanuc.com.cn/IEAMService/AddAmPartsMasterNResponse")]
        System.Threading.Tasks.Task<bool> AddAmPartsMasterNAsync(BFM.ContractModel.AmPartsMasterN mAmPartsMasterN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/UpdateAmPartsMasterN", ReplyAction="http://fanuc.com.cn/IEAMService/UpdateAmPartsMasterNResponse")]
        bool UpdateAmPartsMasterN(BFM.ContractModel.AmPartsMasterN mAmPartsMasterN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/UpdateAmPartsMasterN", ReplyAction="http://fanuc.com.cn/IEAMService/UpdateAmPartsMasterNResponse")]
        System.Threading.Tasks.Task<bool> UpdateAmPartsMasterNAsync(BFM.ContractModel.AmPartsMasterN mAmPartsMasterN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/DelAmPartsMasterNs", ReplyAction="http://fanuc.com.cn/IEAMService/DelAmPartsMasterNsResponse")]
        bool DelAmPartsMasterNs(System.Collections.Generic.List<string> Ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/DelAmPartsMasterNs", ReplyAction="http://fanuc.com.cn/IEAMService/DelAmPartsMasterNsResponse")]
        System.Threading.Tasks.Task<bool> DelAmPartsMasterNsAsync(System.Collections.Generic.List<string> Ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/DelAmPartsMasterN", ReplyAction="http://fanuc.com.cn/IEAMService/DelAmPartsMasterNResponse")]
        bool DelAmPartsMasterN(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/DelAmPartsMasterN", ReplyAction="http://fanuc.com.cn/IEAMService/DelAmPartsMasterNResponse")]
        System.Threading.Tasks.Task<bool> DelAmPartsMasterNAsync(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/GetAmPartsMasterNs", ReplyAction="http://fanuc.com.cn/IEAMService/GetAmPartsMasterNsResponse")]
        System.Collections.Generic.List<BFM.ContractModel.AmPartsMasterN> GetAmPartsMasterNs(string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/GetAmPartsMasterNs", ReplyAction="http://fanuc.com.cn/IEAMService/GetAmPartsMasterNsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BFM.ContractModel.AmPartsMasterN>> GetAmPartsMasterNsAsync(string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/GetAmPartsMasterNById", ReplyAction="http://fanuc.com.cn/IEAMService/GetAmPartsMasterNByIdResponse")]
        BFM.ContractModel.AmPartsMasterN GetAmPartsMasterNById(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/GetAmPartsMasterNById", ReplyAction="http://fanuc.com.cn/IEAMService/GetAmPartsMasterNByIdResponse")]
        System.Threading.Tasks.Task<BFM.ContractModel.AmPartsMasterN> GetAmPartsMasterNByIdAsync(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/GetRsMaintainStandardsByPage", ReplyAction="http://fanuc.com.cn/IEAMService/GetRsMaintainStandardsByPageResponse")]
        System.Collections.Generic.List<BFM.ContractModel.RsMaintainStandards> GetRsMaintainStandardsByPage(int pageSize, int pageIndex, bool isAsc, string orderField, string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/GetRsMaintainStandardsByPage", ReplyAction="http://fanuc.com.cn/IEAMService/GetRsMaintainStandardsByPageResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BFM.ContractModel.RsMaintainStandards>> GetRsMaintainStandardsByPageAsync(int pageSize, int pageIndex, bool isAsc, string orderField, string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/GetRsMaintainStandardsCount", ReplyAction="http://fanuc.com.cn/IEAMService/GetRsMaintainStandardsCountResponse")]
        int GetRsMaintainStandardsCount(string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/GetRsMaintainStandardsCount", ReplyAction="http://fanuc.com.cn/IEAMService/GetRsMaintainStandardsCountResponse")]
        System.Threading.Tasks.Task<int> GetRsMaintainStandardsCountAsync(string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/AddRsMaintainStandards", ReplyAction="http://fanuc.com.cn/IEAMService/AddRsMaintainStandardsResponse")]
        bool AddRsMaintainStandards(BFM.ContractModel.RsMaintainStandards mRsMaintainStandards);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/AddRsMaintainStandards", ReplyAction="http://fanuc.com.cn/IEAMService/AddRsMaintainStandardsResponse")]
        System.Threading.Tasks.Task<bool> AddRsMaintainStandardsAsync(BFM.ContractModel.RsMaintainStandards mRsMaintainStandards);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/UpdateRsMaintainStandards", ReplyAction="http://fanuc.com.cn/IEAMService/UpdateRsMaintainStandardsResponse")]
        bool UpdateRsMaintainStandards(BFM.ContractModel.RsMaintainStandards mRsMaintainStandards);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/UpdateRsMaintainStandards", ReplyAction="http://fanuc.com.cn/IEAMService/UpdateRsMaintainStandardsResponse")]
        System.Threading.Tasks.Task<bool> UpdateRsMaintainStandardsAsync(BFM.ContractModel.RsMaintainStandards mRsMaintainStandards);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/DelRsMaintainStandardss", ReplyAction="http://fanuc.com.cn/IEAMService/DelRsMaintainStandardssResponse")]
        bool DelRsMaintainStandardss(System.Collections.Generic.List<string> Ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/DelRsMaintainStandardss", ReplyAction="http://fanuc.com.cn/IEAMService/DelRsMaintainStandardssResponse")]
        System.Threading.Tasks.Task<bool> DelRsMaintainStandardssAsync(System.Collections.Generic.List<string> Ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/DelRsMaintainStandards", ReplyAction="http://fanuc.com.cn/IEAMService/DelRsMaintainStandardsResponse")]
        bool DelRsMaintainStandards(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/DelRsMaintainStandards", ReplyAction="http://fanuc.com.cn/IEAMService/DelRsMaintainStandardsResponse")]
        System.Threading.Tasks.Task<bool> DelRsMaintainStandardsAsync(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/GetRsMaintainStandardss", ReplyAction="http://fanuc.com.cn/IEAMService/GetRsMaintainStandardssResponse")]
        System.Collections.Generic.List<BFM.ContractModel.RsMaintainStandards> GetRsMaintainStandardss(string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/GetRsMaintainStandardss", ReplyAction="http://fanuc.com.cn/IEAMService/GetRsMaintainStandardssResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BFM.ContractModel.RsMaintainStandards>> GetRsMaintainStandardssAsync(string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/GetRsMaintainStandardsById", ReplyAction="http://fanuc.com.cn/IEAMService/GetRsMaintainStandardsByIdResponse")]
        BFM.ContractModel.RsMaintainStandards GetRsMaintainStandardsById(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/GetRsMaintainStandardsById", ReplyAction="http://fanuc.com.cn/IEAMService/GetRsMaintainStandardsByIdResponse")]
        System.Threading.Tasks.Task<BFM.ContractModel.RsMaintainStandards> GetRsMaintainStandardsByIdAsync(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/GetRsMaintainStandardsDetailByPage", ReplyAction="http://fanuc.com.cn/IEAMService/GetRsMaintainStandardsDetailByPageResponse")]
        System.Collections.Generic.List<BFM.ContractModel.RsMaintainStandardsDetail> GetRsMaintainStandardsDetailByPage(int pageSize, int pageIndex, bool isAsc, string orderField, string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/GetRsMaintainStandardsDetailByPage", ReplyAction="http://fanuc.com.cn/IEAMService/GetRsMaintainStandardsDetailByPageResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BFM.ContractModel.RsMaintainStandardsDetail>> GetRsMaintainStandardsDetailByPageAsync(int pageSize, int pageIndex, bool isAsc, string orderField, string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/GetRsMaintainStandardsDetailCount", ReplyAction="http://fanuc.com.cn/IEAMService/GetRsMaintainStandardsDetailCountResponse")]
        int GetRsMaintainStandardsDetailCount(string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/GetRsMaintainStandardsDetailCount", ReplyAction="http://fanuc.com.cn/IEAMService/GetRsMaintainStandardsDetailCountResponse")]
        System.Threading.Tasks.Task<int> GetRsMaintainStandardsDetailCountAsync(string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/AddRsMaintainStandardsDetail", ReplyAction="http://fanuc.com.cn/IEAMService/AddRsMaintainStandardsDetailResponse")]
        bool AddRsMaintainStandardsDetail(BFM.ContractModel.RsMaintainStandardsDetail mRsMaintainStandardsDetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/AddRsMaintainStandardsDetail", ReplyAction="http://fanuc.com.cn/IEAMService/AddRsMaintainStandardsDetailResponse")]
        System.Threading.Tasks.Task<bool> AddRsMaintainStandardsDetailAsync(BFM.ContractModel.RsMaintainStandardsDetail mRsMaintainStandardsDetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/UpdateRsMaintainStandardsDetail", ReplyAction="http://fanuc.com.cn/IEAMService/UpdateRsMaintainStandardsDetailResponse")]
        bool UpdateRsMaintainStandardsDetail(BFM.ContractModel.RsMaintainStandardsDetail mRsMaintainStandardsDetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/UpdateRsMaintainStandardsDetail", ReplyAction="http://fanuc.com.cn/IEAMService/UpdateRsMaintainStandardsDetailResponse")]
        System.Threading.Tasks.Task<bool> UpdateRsMaintainStandardsDetailAsync(BFM.ContractModel.RsMaintainStandardsDetail mRsMaintainStandardsDetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/DelRsMaintainStandardsDetails", ReplyAction="http://fanuc.com.cn/IEAMService/DelRsMaintainStandardsDetailsResponse")]
        bool DelRsMaintainStandardsDetails(System.Collections.Generic.List<string> Ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/DelRsMaintainStandardsDetails", ReplyAction="http://fanuc.com.cn/IEAMService/DelRsMaintainStandardsDetailsResponse")]
        System.Threading.Tasks.Task<bool> DelRsMaintainStandardsDetailsAsync(System.Collections.Generic.List<string> Ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/DelRsMaintainStandardsDetail", ReplyAction="http://fanuc.com.cn/IEAMService/DelRsMaintainStandardsDetailResponse")]
        bool DelRsMaintainStandardsDetail(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/DelRsMaintainStandardsDetail", ReplyAction="http://fanuc.com.cn/IEAMService/DelRsMaintainStandardsDetailResponse")]
        System.Threading.Tasks.Task<bool> DelRsMaintainStandardsDetailAsync(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/GetRsMaintainStandardsDetails", ReplyAction="http://fanuc.com.cn/IEAMService/GetRsMaintainStandardsDetailsResponse")]
        System.Collections.Generic.List<BFM.ContractModel.RsMaintainStandardsDetail> GetRsMaintainStandardsDetails(string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/GetRsMaintainStandardsDetails", ReplyAction="http://fanuc.com.cn/IEAMService/GetRsMaintainStandardsDetailsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BFM.ContractModel.RsMaintainStandardsDetail>> GetRsMaintainStandardsDetailsAsync(string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/GetRsMaintainStandardsDetailById", ReplyAction="http://fanuc.com.cn/IEAMService/GetRsMaintainStandardsDetailByIdResponse")]
        BFM.ContractModel.RsMaintainStandardsDetail GetRsMaintainStandardsDetailById(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/GetRsMaintainStandardsDetailById", ReplyAction="http://fanuc.com.cn/IEAMService/GetRsMaintainStandardsDetailByIdResponse")]
        System.Threading.Tasks.Task<BFM.ContractModel.RsMaintainStandardsDetail> GetRsMaintainStandardsDetailByIdAsync(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/GetRsMaintainStandardsRelateByPage", ReplyAction="http://fanuc.com.cn/IEAMService/GetRsMaintainStandardsRelateByPageResponse")]
        System.Collections.Generic.List<BFM.ContractModel.RsMaintainStandardsRelate> GetRsMaintainStandardsRelateByPage(int pageSize, int pageIndex, bool isAsc, string orderField, string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/GetRsMaintainStandardsRelateByPage", ReplyAction="http://fanuc.com.cn/IEAMService/GetRsMaintainStandardsRelateByPageResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BFM.ContractModel.RsMaintainStandardsRelate>> GetRsMaintainStandardsRelateByPageAsync(int pageSize, int pageIndex, bool isAsc, string orderField, string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/GetRsMaintainStandardsRelateCount", ReplyAction="http://fanuc.com.cn/IEAMService/GetRsMaintainStandardsRelateCountResponse")]
        int GetRsMaintainStandardsRelateCount(string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/GetRsMaintainStandardsRelateCount", ReplyAction="http://fanuc.com.cn/IEAMService/GetRsMaintainStandardsRelateCountResponse")]
        System.Threading.Tasks.Task<int> GetRsMaintainStandardsRelateCountAsync(string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/AddRsMaintainStandardsRelate", ReplyAction="http://fanuc.com.cn/IEAMService/AddRsMaintainStandardsRelateResponse")]
        bool AddRsMaintainStandardsRelate(BFM.ContractModel.RsMaintainStandardsRelate mRsMaintainStandardsRelate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/AddRsMaintainStandardsRelate", ReplyAction="http://fanuc.com.cn/IEAMService/AddRsMaintainStandardsRelateResponse")]
        System.Threading.Tasks.Task<bool> AddRsMaintainStandardsRelateAsync(BFM.ContractModel.RsMaintainStandardsRelate mRsMaintainStandardsRelate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/UpdateRsMaintainStandardsRelate", ReplyAction="http://fanuc.com.cn/IEAMService/UpdateRsMaintainStandardsRelateResponse")]
        bool UpdateRsMaintainStandardsRelate(BFM.ContractModel.RsMaintainStandardsRelate mRsMaintainStandardsRelate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/UpdateRsMaintainStandardsRelate", ReplyAction="http://fanuc.com.cn/IEAMService/UpdateRsMaintainStandardsRelateResponse")]
        System.Threading.Tasks.Task<bool> UpdateRsMaintainStandardsRelateAsync(BFM.ContractModel.RsMaintainStandardsRelate mRsMaintainStandardsRelate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/DelRsMaintainStandardsRelates", ReplyAction="http://fanuc.com.cn/IEAMService/DelRsMaintainStandardsRelatesResponse")]
        bool DelRsMaintainStandardsRelates(System.Collections.Generic.List<string> Ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/DelRsMaintainStandardsRelates", ReplyAction="http://fanuc.com.cn/IEAMService/DelRsMaintainStandardsRelatesResponse")]
        System.Threading.Tasks.Task<bool> DelRsMaintainStandardsRelatesAsync(System.Collections.Generic.List<string> Ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/DelRsMaintainStandardsRelate", ReplyAction="http://fanuc.com.cn/IEAMService/DelRsMaintainStandardsRelateResponse")]
        bool DelRsMaintainStandardsRelate(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/DelRsMaintainStandardsRelate", ReplyAction="http://fanuc.com.cn/IEAMService/DelRsMaintainStandardsRelateResponse")]
        System.Threading.Tasks.Task<bool> DelRsMaintainStandardsRelateAsync(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/GetRsMaintainStandardsRelates", ReplyAction="http://fanuc.com.cn/IEAMService/GetRsMaintainStandardsRelatesResponse")]
        System.Collections.Generic.List<BFM.ContractModel.RsMaintainStandardsRelate> GetRsMaintainStandardsRelates(string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/GetRsMaintainStandardsRelates", ReplyAction="http://fanuc.com.cn/IEAMService/GetRsMaintainStandardsRelatesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BFM.ContractModel.RsMaintainStandardsRelate>> GetRsMaintainStandardsRelatesAsync(string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/GetRsMaintainStandardsRelateById", ReplyAction="http://fanuc.com.cn/IEAMService/GetRsMaintainStandardsRelateByIdResponse")]
        BFM.ContractModel.RsMaintainStandardsRelate GetRsMaintainStandardsRelateById(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/GetRsMaintainStandardsRelateById", ReplyAction="http://fanuc.com.cn/IEAMService/GetRsMaintainStandardsRelateByIdResponse")]
        System.Threading.Tasks.Task<BFM.ContractModel.RsMaintainStandardsRelate> GetRsMaintainStandardsRelateByIdAsync(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/GetRmRepairRecordByPage", ReplyAction="http://fanuc.com.cn/IEAMService/GetRmRepairRecordByPageResponse")]
        System.Collections.Generic.List<BFM.ContractModel.RmRepairRecord> GetRmRepairRecordByPage(int pageSize, int pageIndex, bool isAsc, string orderField, string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/GetRmRepairRecordByPage", ReplyAction="http://fanuc.com.cn/IEAMService/GetRmRepairRecordByPageResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BFM.ContractModel.RmRepairRecord>> GetRmRepairRecordByPageAsync(int pageSize, int pageIndex, bool isAsc, string orderField, string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/GetRmRepairRecordCount", ReplyAction="http://fanuc.com.cn/IEAMService/GetRmRepairRecordCountResponse")]
        int GetRmRepairRecordCount(string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/GetRmRepairRecordCount", ReplyAction="http://fanuc.com.cn/IEAMService/GetRmRepairRecordCountResponse")]
        System.Threading.Tasks.Task<int> GetRmRepairRecordCountAsync(string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/AddRmRepairRecord", ReplyAction="http://fanuc.com.cn/IEAMService/AddRmRepairRecordResponse")]
        bool AddRmRepairRecord(BFM.ContractModel.RmRepairRecord mRmRepairRecord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/AddRmRepairRecord", ReplyAction="http://fanuc.com.cn/IEAMService/AddRmRepairRecordResponse")]
        System.Threading.Tasks.Task<bool> AddRmRepairRecordAsync(BFM.ContractModel.RmRepairRecord mRmRepairRecord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/UpdateRmRepairRecord", ReplyAction="http://fanuc.com.cn/IEAMService/UpdateRmRepairRecordResponse")]
        bool UpdateRmRepairRecord(BFM.ContractModel.RmRepairRecord mRmRepairRecord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/UpdateRmRepairRecord", ReplyAction="http://fanuc.com.cn/IEAMService/UpdateRmRepairRecordResponse")]
        System.Threading.Tasks.Task<bool> UpdateRmRepairRecordAsync(BFM.ContractModel.RmRepairRecord mRmRepairRecord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/DelRmRepairRecords", ReplyAction="http://fanuc.com.cn/IEAMService/DelRmRepairRecordsResponse")]
        bool DelRmRepairRecords(System.Collections.Generic.List<string> Ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/DelRmRepairRecords", ReplyAction="http://fanuc.com.cn/IEAMService/DelRmRepairRecordsResponse")]
        System.Threading.Tasks.Task<bool> DelRmRepairRecordsAsync(System.Collections.Generic.List<string> Ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/DelRmRepairRecord", ReplyAction="http://fanuc.com.cn/IEAMService/DelRmRepairRecordResponse")]
        bool DelRmRepairRecord(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/DelRmRepairRecord", ReplyAction="http://fanuc.com.cn/IEAMService/DelRmRepairRecordResponse")]
        System.Threading.Tasks.Task<bool> DelRmRepairRecordAsync(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/GetRmRepairRecords", ReplyAction="http://fanuc.com.cn/IEAMService/GetRmRepairRecordsResponse")]
        System.Collections.Generic.List<BFM.ContractModel.RmRepairRecord> GetRmRepairRecords(string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/GetRmRepairRecords", ReplyAction="http://fanuc.com.cn/IEAMService/GetRmRepairRecordsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BFM.ContractModel.RmRepairRecord>> GetRmRepairRecordsAsync(string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/GetRmRepairRecordById", ReplyAction="http://fanuc.com.cn/IEAMService/GetRmRepairRecordByIdResponse")]
        BFM.ContractModel.RmRepairRecord GetRmRepairRecordById(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/GetRmRepairRecordById", ReplyAction="http://fanuc.com.cn/IEAMService/GetRmRepairRecordByIdResponse")]
        System.Threading.Tasks.Task<BFM.ContractModel.RmRepairRecord> GetRmRepairRecordByIdAsync(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/GetRsMaintainRecordByPage", ReplyAction="http://fanuc.com.cn/IEAMService/GetRsMaintainRecordByPageResponse")]
        System.Collections.Generic.List<BFM.ContractModel.RsMaintainRecord> GetRsMaintainRecordByPage(int pageSize, int pageIndex, bool isAsc, string orderField, string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/GetRsMaintainRecordByPage", ReplyAction="http://fanuc.com.cn/IEAMService/GetRsMaintainRecordByPageResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BFM.ContractModel.RsMaintainRecord>> GetRsMaintainRecordByPageAsync(int pageSize, int pageIndex, bool isAsc, string orderField, string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/GetRsMaintainRecordCount", ReplyAction="http://fanuc.com.cn/IEAMService/GetRsMaintainRecordCountResponse")]
        int GetRsMaintainRecordCount(string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/GetRsMaintainRecordCount", ReplyAction="http://fanuc.com.cn/IEAMService/GetRsMaintainRecordCountResponse")]
        System.Threading.Tasks.Task<int> GetRsMaintainRecordCountAsync(string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/AddRsMaintainRecord", ReplyAction="http://fanuc.com.cn/IEAMService/AddRsMaintainRecordResponse")]
        bool AddRsMaintainRecord(BFM.ContractModel.RsMaintainRecord mRsMaintainRecord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/AddRsMaintainRecord", ReplyAction="http://fanuc.com.cn/IEAMService/AddRsMaintainRecordResponse")]
        System.Threading.Tasks.Task<bool> AddRsMaintainRecordAsync(BFM.ContractModel.RsMaintainRecord mRsMaintainRecord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/UpdateRsMaintainRecord", ReplyAction="http://fanuc.com.cn/IEAMService/UpdateRsMaintainRecordResponse")]
        bool UpdateRsMaintainRecord(BFM.ContractModel.RsMaintainRecord mRsMaintainRecord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/UpdateRsMaintainRecord", ReplyAction="http://fanuc.com.cn/IEAMService/UpdateRsMaintainRecordResponse")]
        System.Threading.Tasks.Task<bool> UpdateRsMaintainRecordAsync(BFM.ContractModel.RsMaintainRecord mRsMaintainRecord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/DelRsMaintainRecords", ReplyAction="http://fanuc.com.cn/IEAMService/DelRsMaintainRecordsResponse")]
        bool DelRsMaintainRecords(System.Collections.Generic.List<string> Ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/DelRsMaintainRecords", ReplyAction="http://fanuc.com.cn/IEAMService/DelRsMaintainRecordsResponse")]
        System.Threading.Tasks.Task<bool> DelRsMaintainRecordsAsync(System.Collections.Generic.List<string> Ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/DelRsMaintainRecord", ReplyAction="http://fanuc.com.cn/IEAMService/DelRsMaintainRecordResponse")]
        bool DelRsMaintainRecord(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/DelRsMaintainRecord", ReplyAction="http://fanuc.com.cn/IEAMService/DelRsMaintainRecordResponse")]
        System.Threading.Tasks.Task<bool> DelRsMaintainRecordAsync(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/GetRsMaintainRecords", ReplyAction="http://fanuc.com.cn/IEAMService/GetRsMaintainRecordsResponse")]
        System.Collections.Generic.List<BFM.ContractModel.RsMaintainRecord> GetRsMaintainRecords(string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/GetRsMaintainRecords", ReplyAction="http://fanuc.com.cn/IEAMService/GetRsMaintainRecordsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BFM.ContractModel.RsMaintainRecord>> GetRsMaintainRecordsAsync(string sWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/GetRsMaintainRecordById", ReplyAction="http://fanuc.com.cn/IEAMService/GetRsMaintainRecordByIdResponse")]
        BFM.ContractModel.RsMaintainRecord GetRsMaintainRecordById(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanuc.com.cn/IEAMService/GetRsMaintainRecordById", ReplyAction="http://fanuc.com.cn/IEAMService/GetRsMaintainRecordByIdResponse")]
        System.Threading.Tasks.Task<BFM.ContractModel.RsMaintainRecord> GetRsMaintainRecordByIdAsync(string Id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEAMServiceChannel : BFM.Server.DataAsset.EAMService.IEAMService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EAMServiceClient : System.ServiceModel.ClientBase<BFM.Server.DataAsset.EAMService.IEAMService>, BFM.Server.DataAsset.EAMService.IEAMService {
        
        public EAMServiceClient() {
        }
        
        public EAMServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EAMServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EAMServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EAMServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<BFM.ContractModel.AmAssetMasterN> GetAmAssetMasterNByPage(int pageSize, int pageIndex, bool isAsc, string orderField, string sWhere) {
            return base.Channel.GetAmAssetMasterNByPage(pageSize, pageIndex, isAsc, orderField, sWhere);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BFM.ContractModel.AmAssetMasterN>> GetAmAssetMasterNByPageAsync(int pageSize, int pageIndex, bool isAsc, string orderField, string sWhere) {
            return base.Channel.GetAmAssetMasterNByPageAsync(pageSize, pageIndex, isAsc, orderField, sWhere);
        }
        
        public int GetAmAssetMasterNCount(string sWhere) {
            return base.Channel.GetAmAssetMasterNCount(sWhere);
        }
        
        public System.Threading.Tasks.Task<int> GetAmAssetMasterNCountAsync(string sWhere) {
            return base.Channel.GetAmAssetMasterNCountAsync(sWhere);
        }
        
        public bool AddAmAssetMasterN(BFM.ContractModel.AmAssetMasterN mAmAssetMasterN) {
            return base.Channel.AddAmAssetMasterN(mAmAssetMasterN);
        }
        
        public System.Threading.Tasks.Task<bool> AddAmAssetMasterNAsync(BFM.ContractModel.AmAssetMasterN mAmAssetMasterN) {
            return base.Channel.AddAmAssetMasterNAsync(mAmAssetMasterN);
        }
        
        public bool UpdateAmAssetMasterN(BFM.ContractModel.AmAssetMasterN mAmAssetMasterN) {
            return base.Channel.UpdateAmAssetMasterN(mAmAssetMasterN);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAmAssetMasterNAsync(BFM.ContractModel.AmAssetMasterN mAmAssetMasterN) {
            return base.Channel.UpdateAmAssetMasterNAsync(mAmAssetMasterN);
        }
        
        public bool DelAmAssetMasterNs(System.Collections.Generic.List<string> Ids) {
            return base.Channel.DelAmAssetMasterNs(Ids);
        }
        
        public System.Threading.Tasks.Task<bool> DelAmAssetMasterNsAsync(System.Collections.Generic.List<string> Ids) {
            return base.Channel.DelAmAssetMasterNsAsync(Ids);
        }
        
        public bool DelAmAssetMasterN(string Id) {
            return base.Channel.DelAmAssetMasterN(Id);
        }
        
        public System.Threading.Tasks.Task<bool> DelAmAssetMasterNAsync(string Id) {
            return base.Channel.DelAmAssetMasterNAsync(Id);
        }
        
        public System.Collections.Generic.List<BFM.ContractModel.AmAssetMasterN> GetAmAssetMasterNs(string sWhere) {
            return base.Channel.GetAmAssetMasterNs(sWhere);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BFM.ContractModel.AmAssetMasterN>> GetAmAssetMasterNsAsync(string sWhere) {
            return base.Channel.GetAmAssetMasterNsAsync(sWhere);
        }
        
        public BFM.ContractModel.AmAssetMasterN GetAmAssetMasterNById(string Id) {
            return base.Channel.GetAmAssetMasterNById(Id);
        }
        
        public System.Threading.Tasks.Task<BFM.ContractModel.AmAssetMasterN> GetAmAssetMasterNByIdAsync(string Id) {
            return base.Channel.GetAmAssetMasterNByIdAsync(Id);
        }
        
        public System.Collections.Generic.List<BFM.ContractModel.AmPartsMasterN> GetAmPartsMasterNByPage(int pageSize, int pageIndex, bool isAsc, string orderField, string sWhere) {
            return base.Channel.GetAmPartsMasterNByPage(pageSize, pageIndex, isAsc, orderField, sWhere);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BFM.ContractModel.AmPartsMasterN>> GetAmPartsMasterNByPageAsync(int pageSize, int pageIndex, bool isAsc, string orderField, string sWhere) {
            return base.Channel.GetAmPartsMasterNByPageAsync(pageSize, pageIndex, isAsc, orderField, sWhere);
        }
        
        public int GetAmPartsMasterNCount(string sWhere) {
            return base.Channel.GetAmPartsMasterNCount(sWhere);
        }
        
        public System.Threading.Tasks.Task<int> GetAmPartsMasterNCountAsync(string sWhere) {
            return base.Channel.GetAmPartsMasterNCountAsync(sWhere);
        }
        
        public bool AddAmPartsMasterN(BFM.ContractModel.AmPartsMasterN mAmPartsMasterN) {
            return base.Channel.AddAmPartsMasterN(mAmPartsMasterN);
        }
        
        public System.Threading.Tasks.Task<bool> AddAmPartsMasterNAsync(BFM.ContractModel.AmPartsMasterN mAmPartsMasterN) {
            return base.Channel.AddAmPartsMasterNAsync(mAmPartsMasterN);
        }
        
        public bool UpdateAmPartsMasterN(BFM.ContractModel.AmPartsMasterN mAmPartsMasterN) {
            return base.Channel.UpdateAmPartsMasterN(mAmPartsMasterN);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAmPartsMasterNAsync(BFM.ContractModel.AmPartsMasterN mAmPartsMasterN) {
            return base.Channel.UpdateAmPartsMasterNAsync(mAmPartsMasterN);
        }
        
        public bool DelAmPartsMasterNs(System.Collections.Generic.List<string> Ids) {
            return base.Channel.DelAmPartsMasterNs(Ids);
        }
        
        public System.Threading.Tasks.Task<bool> DelAmPartsMasterNsAsync(System.Collections.Generic.List<string> Ids) {
            return base.Channel.DelAmPartsMasterNsAsync(Ids);
        }
        
        public bool DelAmPartsMasterN(string Id) {
            return base.Channel.DelAmPartsMasterN(Id);
        }
        
        public System.Threading.Tasks.Task<bool> DelAmPartsMasterNAsync(string Id) {
            return base.Channel.DelAmPartsMasterNAsync(Id);
        }
        
        public System.Collections.Generic.List<BFM.ContractModel.AmPartsMasterN> GetAmPartsMasterNs(string sWhere) {
            return base.Channel.GetAmPartsMasterNs(sWhere);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BFM.ContractModel.AmPartsMasterN>> GetAmPartsMasterNsAsync(string sWhere) {
            return base.Channel.GetAmPartsMasterNsAsync(sWhere);
        }
        
        public BFM.ContractModel.AmPartsMasterN GetAmPartsMasterNById(string Id) {
            return base.Channel.GetAmPartsMasterNById(Id);
        }
        
        public System.Threading.Tasks.Task<BFM.ContractModel.AmPartsMasterN> GetAmPartsMasterNByIdAsync(string Id) {
            return base.Channel.GetAmPartsMasterNByIdAsync(Id);
        }
        
        public System.Collections.Generic.List<BFM.ContractModel.RsMaintainStandards> GetRsMaintainStandardsByPage(int pageSize, int pageIndex, bool isAsc, string orderField, string sWhere) {
            return base.Channel.GetRsMaintainStandardsByPage(pageSize, pageIndex, isAsc, orderField, sWhere);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BFM.ContractModel.RsMaintainStandards>> GetRsMaintainStandardsByPageAsync(int pageSize, int pageIndex, bool isAsc, string orderField, string sWhere) {
            return base.Channel.GetRsMaintainStandardsByPageAsync(pageSize, pageIndex, isAsc, orderField, sWhere);
        }
        
        public int GetRsMaintainStandardsCount(string sWhere) {
            return base.Channel.GetRsMaintainStandardsCount(sWhere);
        }
        
        public System.Threading.Tasks.Task<int> GetRsMaintainStandardsCountAsync(string sWhere) {
            return base.Channel.GetRsMaintainStandardsCountAsync(sWhere);
        }
        
        public bool AddRsMaintainStandards(BFM.ContractModel.RsMaintainStandards mRsMaintainStandards) {
            return base.Channel.AddRsMaintainStandards(mRsMaintainStandards);
        }
        
        public System.Threading.Tasks.Task<bool> AddRsMaintainStandardsAsync(BFM.ContractModel.RsMaintainStandards mRsMaintainStandards) {
            return base.Channel.AddRsMaintainStandardsAsync(mRsMaintainStandards);
        }
        
        public bool UpdateRsMaintainStandards(BFM.ContractModel.RsMaintainStandards mRsMaintainStandards) {
            return base.Channel.UpdateRsMaintainStandards(mRsMaintainStandards);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateRsMaintainStandardsAsync(BFM.ContractModel.RsMaintainStandards mRsMaintainStandards) {
            return base.Channel.UpdateRsMaintainStandardsAsync(mRsMaintainStandards);
        }
        
        public bool DelRsMaintainStandardss(System.Collections.Generic.List<string> Ids) {
            return base.Channel.DelRsMaintainStandardss(Ids);
        }
        
        public System.Threading.Tasks.Task<bool> DelRsMaintainStandardssAsync(System.Collections.Generic.List<string> Ids) {
            return base.Channel.DelRsMaintainStandardssAsync(Ids);
        }
        
        public bool DelRsMaintainStandards(string Id) {
            return base.Channel.DelRsMaintainStandards(Id);
        }
        
        public System.Threading.Tasks.Task<bool> DelRsMaintainStandardsAsync(string Id) {
            return base.Channel.DelRsMaintainStandardsAsync(Id);
        }
        
        public System.Collections.Generic.List<BFM.ContractModel.RsMaintainStandards> GetRsMaintainStandardss(string sWhere) {
            return base.Channel.GetRsMaintainStandardss(sWhere);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BFM.ContractModel.RsMaintainStandards>> GetRsMaintainStandardssAsync(string sWhere) {
            return base.Channel.GetRsMaintainStandardssAsync(sWhere);
        }
        
        public BFM.ContractModel.RsMaintainStandards GetRsMaintainStandardsById(string Id) {
            return base.Channel.GetRsMaintainStandardsById(Id);
        }
        
        public System.Threading.Tasks.Task<BFM.ContractModel.RsMaintainStandards> GetRsMaintainStandardsByIdAsync(string Id) {
            return base.Channel.GetRsMaintainStandardsByIdAsync(Id);
        }
        
        public System.Collections.Generic.List<BFM.ContractModel.RsMaintainStandardsDetail> GetRsMaintainStandardsDetailByPage(int pageSize, int pageIndex, bool isAsc, string orderField, string sWhere) {
            return base.Channel.GetRsMaintainStandardsDetailByPage(pageSize, pageIndex, isAsc, orderField, sWhere);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BFM.ContractModel.RsMaintainStandardsDetail>> GetRsMaintainStandardsDetailByPageAsync(int pageSize, int pageIndex, bool isAsc, string orderField, string sWhere) {
            return base.Channel.GetRsMaintainStandardsDetailByPageAsync(pageSize, pageIndex, isAsc, orderField, sWhere);
        }
        
        public int GetRsMaintainStandardsDetailCount(string sWhere) {
            return base.Channel.GetRsMaintainStandardsDetailCount(sWhere);
        }
        
        public System.Threading.Tasks.Task<int> GetRsMaintainStandardsDetailCountAsync(string sWhere) {
            return base.Channel.GetRsMaintainStandardsDetailCountAsync(sWhere);
        }
        
        public bool AddRsMaintainStandardsDetail(BFM.ContractModel.RsMaintainStandardsDetail mRsMaintainStandardsDetail) {
            return base.Channel.AddRsMaintainStandardsDetail(mRsMaintainStandardsDetail);
        }
        
        public System.Threading.Tasks.Task<bool> AddRsMaintainStandardsDetailAsync(BFM.ContractModel.RsMaintainStandardsDetail mRsMaintainStandardsDetail) {
            return base.Channel.AddRsMaintainStandardsDetailAsync(mRsMaintainStandardsDetail);
        }
        
        public bool UpdateRsMaintainStandardsDetail(BFM.ContractModel.RsMaintainStandardsDetail mRsMaintainStandardsDetail) {
            return base.Channel.UpdateRsMaintainStandardsDetail(mRsMaintainStandardsDetail);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateRsMaintainStandardsDetailAsync(BFM.ContractModel.RsMaintainStandardsDetail mRsMaintainStandardsDetail) {
            return base.Channel.UpdateRsMaintainStandardsDetailAsync(mRsMaintainStandardsDetail);
        }
        
        public bool DelRsMaintainStandardsDetails(System.Collections.Generic.List<string> Ids) {
            return base.Channel.DelRsMaintainStandardsDetails(Ids);
        }
        
        public System.Threading.Tasks.Task<bool> DelRsMaintainStandardsDetailsAsync(System.Collections.Generic.List<string> Ids) {
            return base.Channel.DelRsMaintainStandardsDetailsAsync(Ids);
        }
        
        public bool DelRsMaintainStandardsDetail(string Id) {
            return base.Channel.DelRsMaintainStandardsDetail(Id);
        }
        
        public System.Threading.Tasks.Task<bool> DelRsMaintainStandardsDetailAsync(string Id) {
            return base.Channel.DelRsMaintainStandardsDetailAsync(Id);
        }
        
        public System.Collections.Generic.List<BFM.ContractModel.RsMaintainStandardsDetail> GetRsMaintainStandardsDetails(string sWhere) {
            return base.Channel.GetRsMaintainStandardsDetails(sWhere);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BFM.ContractModel.RsMaintainStandardsDetail>> GetRsMaintainStandardsDetailsAsync(string sWhere) {
            return base.Channel.GetRsMaintainStandardsDetailsAsync(sWhere);
        }
        
        public BFM.ContractModel.RsMaintainStandardsDetail GetRsMaintainStandardsDetailById(string Id) {
            return base.Channel.GetRsMaintainStandardsDetailById(Id);
        }
        
        public System.Threading.Tasks.Task<BFM.ContractModel.RsMaintainStandardsDetail> GetRsMaintainStandardsDetailByIdAsync(string Id) {
            return base.Channel.GetRsMaintainStandardsDetailByIdAsync(Id);
        }
        
        public System.Collections.Generic.List<BFM.ContractModel.RsMaintainStandardsRelate> GetRsMaintainStandardsRelateByPage(int pageSize, int pageIndex, bool isAsc, string orderField, string sWhere) {
            return base.Channel.GetRsMaintainStandardsRelateByPage(pageSize, pageIndex, isAsc, orderField, sWhere);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BFM.ContractModel.RsMaintainStandardsRelate>> GetRsMaintainStandardsRelateByPageAsync(int pageSize, int pageIndex, bool isAsc, string orderField, string sWhere) {
            return base.Channel.GetRsMaintainStandardsRelateByPageAsync(pageSize, pageIndex, isAsc, orderField, sWhere);
        }
        
        public int GetRsMaintainStandardsRelateCount(string sWhere) {
            return base.Channel.GetRsMaintainStandardsRelateCount(sWhere);
        }
        
        public System.Threading.Tasks.Task<int> GetRsMaintainStandardsRelateCountAsync(string sWhere) {
            return base.Channel.GetRsMaintainStandardsRelateCountAsync(sWhere);
        }
        
        public bool AddRsMaintainStandardsRelate(BFM.ContractModel.RsMaintainStandardsRelate mRsMaintainStandardsRelate) {
            return base.Channel.AddRsMaintainStandardsRelate(mRsMaintainStandardsRelate);
        }
        
        public System.Threading.Tasks.Task<bool> AddRsMaintainStandardsRelateAsync(BFM.ContractModel.RsMaintainStandardsRelate mRsMaintainStandardsRelate) {
            return base.Channel.AddRsMaintainStandardsRelateAsync(mRsMaintainStandardsRelate);
        }
        
        public bool UpdateRsMaintainStandardsRelate(BFM.ContractModel.RsMaintainStandardsRelate mRsMaintainStandardsRelate) {
            return base.Channel.UpdateRsMaintainStandardsRelate(mRsMaintainStandardsRelate);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateRsMaintainStandardsRelateAsync(BFM.ContractModel.RsMaintainStandardsRelate mRsMaintainStandardsRelate) {
            return base.Channel.UpdateRsMaintainStandardsRelateAsync(mRsMaintainStandardsRelate);
        }
        
        public bool DelRsMaintainStandardsRelates(System.Collections.Generic.List<string> Ids) {
            return base.Channel.DelRsMaintainStandardsRelates(Ids);
        }
        
        public System.Threading.Tasks.Task<bool> DelRsMaintainStandardsRelatesAsync(System.Collections.Generic.List<string> Ids) {
            return base.Channel.DelRsMaintainStandardsRelatesAsync(Ids);
        }
        
        public bool DelRsMaintainStandardsRelate(string Id) {
            return base.Channel.DelRsMaintainStandardsRelate(Id);
        }
        
        public System.Threading.Tasks.Task<bool> DelRsMaintainStandardsRelateAsync(string Id) {
            return base.Channel.DelRsMaintainStandardsRelateAsync(Id);
        }
        
        public System.Collections.Generic.List<BFM.ContractModel.RsMaintainStandardsRelate> GetRsMaintainStandardsRelates(string sWhere) {
            return base.Channel.GetRsMaintainStandardsRelates(sWhere);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BFM.ContractModel.RsMaintainStandardsRelate>> GetRsMaintainStandardsRelatesAsync(string sWhere) {
            return base.Channel.GetRsMaintainStandardsRelatesAsync(sWhere);
        }
        
        public BFM.ContractModel.RsMaintainStandardsRelate GetRsMaintainStandardsRelateById(string Id) {
            return base.Channel.GetRsMaintainStandardsRelateById(Id);
        }
        
        public System.Threading.Tasks.Task<BFM.ContractModel.RsMaintainStandardsRelate> GetRsMaintainStandardsRelateByIdAsync(string Id) {
            return base.Channel.GetRsMaintainStandardsRelateByIdAsync(Id);
        }
        
        public System.Collections.Generic.List<BFM.ContractModel.RmRepairRecord> GetRmRepairRecordByPage(int pageSize, int pageIndex, bool isAsc, string orderField, string sWhere) {
            return base.Channel.GetRmRepairRecordByPage(pageSize, pageIndex, isAsc, orderField, sWhere);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BFM.ContractModel.RmRepairRecord>> GetRmRepairRecordByPageAsync(int pageSize, int pageIndex, bool isAsc, string orderField, string sWhere) {
            return base.Channel.GetRmRepairRecordByPageAsync(pageSize, pageIndex, isAsc, orderField, sWhere);
        }
        
        public int GetRmRepairRecordCount(string sWhere) {
            return base.Channel.GetRmRepairRecordCount(sWhere);
        }
        
        public System.Threading.Tasks.Task<int> GetRmRepairRecordCountAsync(string sWhere) {
            return base.Channel.GetRmRepairRecordCountAsync(sWhere);
        }
        
        public bool AddRmRepairRecord(BFM.ContractModel.RmRepairRecord mRmRepairRecord) {
            return base.Channel.AddRmRepairRecord(mRmRepairRecord);
        }
        
        public System.Threading.Tasks.Task<bool> AddRmRepairRecordAsync(BFM.ContractModel.RmRepairRecord mRmRepairRecord) {
            return base.Channel.AddRmRepairRecordAsync(mRmRepairRecord);
        }
        
        public bool UpdateRmRepairRecord(BFM.ContractModel.RmRepairRecord mRmRepairRecord) {
            return base.Channel.UpdateRmRepairRecord(mRmRepairRecord);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateRmRepairRecordAsync(BFM.ContractModel.RmRepairRecord mRmRepairRecord) {
            return base.Channel.UpdateRmRepairRecordAsync(mRmRepairRecord);
        }
        
        public bool DelRmRepairRecords(System.Collections.Generic.List<string> Ids) {
            return base.Channel.DelRmRepairRecords(Ids);
        }
        
        public System.Threading.Tasks.Task<bool> DelRmRepairRecordsAsync(System.Collections.Generic.List<string> Ids) {
            return base.Channel.DelRmRepairRecordsAsync(Ids);
        }
        
        public bool DelRmRepairRecord(string Id) {
            return base.Channel.DelRmRepairRecord(Id);
        }
        
        public System.Threading.Tasks.Task<bool> DelRmRepairRecordAsync(string Id) {
            return base.Channel.DelRmRepairRecordAsync(Id);
        }
        
        public System.Collections.Generic.List<BFM.ContractModel.RmRepairRecord> GetRmRepairRecords(string sWhere) {
            return base.Channel.GetRmRepairRecords(sWhere);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BFM.ContractModel.RmRepairRecord>> GetRmRepairRecordsAsync(string sWhere) {
            return base.Channel.GetRmRepairRecordsAsync(sWhere);
        }
        
        public BFM.ContractModel.RmRepairRecord GetRmRepairRecordById(string Id) {
            return base.Channel.GetRmRepairRecordById(Id);
        }
        
        public System.Threading.Tasks.Task<BFM.ContractModel.RmRepairRecord> GetRmRepairRecordByIdAsync(string Id) {
            return base.Channel.GetRmRepairRecordByIdAsync(Id);
        }
        
        public System.Collections.Generic.List<BFM.ContractModel.RsMaintainRecord> GetRsMaintainRecordByPage(int pageSize, int pageIndex, bool isAsc, string orderField, string sWhere) {
            return base.Channel.GetRsMaintainRecordByPage(pageSize, pageIndex, isAsc, orderField, sWhere);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BFM.ContractModel.RsMaintainRecord>> GetRsMaintainRecordByPageAsync(int pageSize, int pageIndex, bool isAsc, string orderField, string sWhere) {
            return base.Channel.GetRsMaintainRecordByPageAsync(pageSize, pageIndex, isAsc, orderField, sWhere);
        }
        
        public int GetRsMaintainRecordCount(string sWhere) {
            return base.Channel.GetRsMaintainRecordCount(sWhere);
        }
        
        public System.Threading.Tasks.Task<int> GetRsMaintainRecordCountAsync(string sWhere) {
            return base.Channel.GetRsMaintainRecordCountAsync(sWhere);
        }
        
        public bool AddRsMaintainRecord(BFM.ContractModel.RsMaintainRecord mRsMaintainRecord) {
            return base.Channel.AddRsMaintainRecord(mRsMaintainRecord);
        }
        
        public System.Threading.Tasks.Task<bool> AddRsMaintainRecordAsync(BFM.ContractModel.RsMaintainRecord mRsMaintainRecord) {
            return base.Channel.AddRsMaintainRecordAsync(mRsMaintainRecord);
        }
        
        public bool UpdateRsMaintainRecord(BFM.ContractModel.RsMaintainRecord mRsMaintainRecord) {
            return base.Channel.UpdateRsMaintainRecord(mRsMaintainRecord);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateRsMaintainRecordAsync(BFM.ContractModel.RsMaintainRecord mRsMaintainRecord) {
            return base.Channel.UpdateRsMaintainRecordAsync(mRsMaintainRecord);
        }
        
        public bool DelRsMaintainRecords(System.Collections.Generic.List<string> Ids) {
            return base.Channel.DelRsMaintainRecords(Ids);
        }
        
        public System.Threading.Tasks.Task<bool> DelRsMaintainRecordsAsync(System.Collections.Generic.List<string> Ids) {
            return base.Channel.DelRsMaintainRecordsAsync(Ids);
        }
        
        public bool DelRsMaintainRecord(string Id) {
            return base.Channel.DelRsMaintainRecord(Id);
        }
        
        public System.Threading.Tasks.Task<bool> DelRsMaintainRecordAsync(string Id) {
            return base.Channel.DelRsMaintainRecordAsync(Id);
        }
        
        public System.Collections.Generic.List<BFM.ContractModel.RsMaintainRecord> GetRsMaintainRecords(string sWhere) {
            return base.Channel.GetRsMaintainRecords(sWhere);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BFM.ContractModel.RsMaintainRecord>> GetRsMaintainRecordsAsync(string sWhere) {
            return base.Channel.GetRsMaintainRecordsAsync(sWhere);
        }
        
        public BFM.ContractModel.RsMaintainRecord GetRsMaintainRecordById(string Id) {
            return base.Channel.GetRsMaintainRecordById(Id);
        }
        
        public System.Threading.Tasks.Task<BFM.ContractModel.RsMaintainRecord> GetRsMaintainRecordByIdAsync(string Id) {
            return base.Channel.GetRsMaintainRecordByIdAsync(Id);
        }
    }
}
